### PR TITLE
Improve Code Quality (6 of x) 

### PR DESCRIPTION
**Pull request by iamcarbon**
This PR:

- Simplifies the syntax used to construct KeyValuePairs and tuples
- Prefers ValueTuple to tuple (when safe)
- Fixes a few spelling errors
- Updates a few variables to const

### CODE REVIEW

**Comment by iamcarbon** [comment]
@PetroProtsyk Ready for review.

**Comment by PetroProtsyk** [comment]
What is the benefit of using `if (index is NoId)` instead of `if (index == NoId)`?

**Comment by iamcarbon** [comment]
The codegen in this case is identical -- so just a style preference.

Let me know if you'd like me to revert these.

**Comment by PetroProtsyk** [comment]
> The codegen in this case is identical -- so just a style preference.
> 
> Let me know if you'd like me to revert these.

Actually, there is a subtle difference: https://stackoverflow.com/questions/40676426/what-is-the-difference-between-x-is-null-and-x-null

**Pull request merged**
